.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 Zhou Mo <cdluminate@gmail.com>,
.TH FORTUNE-ZH "6"

.SH NAME
fortune-zh \- Chinese Data files for fortune

.SH SYNOPSIS
.B fortune-zh [old]
.br
.B fortune <DATAFILE>

.SH OPTIONS
.I old
  Only show the content in tang300 and song100.

.SH DESCRIPTION
fortune-zh is a simple shell script that invokes fortune with Chinese data files,
while the package "fortune-zh" contains mainly the Chinese Data files, including
some Chinese classical poetries.

.SH EXAMPLE
.RS
# this is the same as "$ fortune-zh old" :
.br
$ fortune 75% tang300 25% song100
.br
# and this is recommended :
.br
$ fortune-zh
.RE

.SH AVAILABLE DATAFILES
.B tang300
.B song100
.B chinese

.SH FILES
.TP
/usr/share/games/fortunes/{tang300,song100,chinese}

.SH SEE ALSO
.BR fortune(6)

.SH MANPAGE BY
Zhou Mo <cdluminate@gmail.com>, 2015.
