.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 Zhou Mo <cdluminate@gmail.com>,
.TH FORTUNE-ZH 6 "April 3, 2015"

.SH NAME
fortune-zh \- Chinese Data files for fortune

.SH SYNOPSIS
.B fortune-zh [ ts | c ]

.SH DESCRIPTION
\fIfortune-zh\fR is a simple shell script that invokes \fIfortune\fR with Chinese data files 
and their preset proportions.
.PP
When execute \fIfortune-zh\fR without args, it would use all available data files of 
fortune-zh. If you want to change this behaviour, please consider the use of options
below or directly invoke \fIfortune\fR with proper proportions by your self.

.SH OPTIONS
.TP
\fBts\fR
Only show cookies in \fBtang300\fR and \fBsong100\fR.

.TP
\fBc\fR
Only show cookies in \fBchinese\fR.

.SH DATAFILE
.TP
.I /usr/share/games/fortunes/tang300
About 300 Poetries from Tang dynasty.

.TP
.I /usr/share/games/fortunes/song100
About 100 Poetries from Song dynasty.

.TP
.I /usr/share/games/fortunes/chinese
Miscellaneous Chinese Culture Cookies, excluding those tang300 and song100 already included.

.SH SEE ALSO
.BR fortune(6)

.SH AUTHOR
fortune-zh was originally created by
.IP
Copyright © 2001-2009 Yu Guanghui <ygh@debian.org>
.PP
This manual page was written by Zhou Mo <cdluminate@gmail.com> for Debian, and may be used by others.
