.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 Zhou Mo <cdluminate@gmail.com>,
.TH FORTUNE-ZH "6"

.SH NAME
fortune-zh \- Chinese Data files for fortune

.SH SYNOPSIS
.B fortune-zh
.br
.B fortune <DATAFILE>

.SH DESCRIPTION
fortune-zh is a simple shell script that invokes fortune with Chinese data files,
while the package "fortune-zh" contains mainly the Chinese Data files, including
some Chinese classical poetries.
.P
However, we recommend the use of 
.RS
$ fortune 75% tang300 25% song100 
.RE
instead of
.RS
$ fortune-zh
.RE

.SH AVAILABLE DATAFILES
.B tang300
.B song100
.B shijing

.SH OPTIONS
There is \fBno\fP option for fortune-zh.

.SH FILES
.TP
/usr/share/games/fortunes/{tang300,song100,shijing}

.SH SEE ALSO
.BR fortune(6)

.SH MANPAGE BY
Zhou Mo <cdluminate@gmail.com>, 2015.
