#!/bin/sh
# fortune-zh
#   invokes fortune with Chinese cookies.

set -e

FORTUNE="/usr/games/fortune"

# the old version (1.*) of fortune-zh only has tang300 and song100
DICT="18% tang300 05% song100 77% chinese"
DICT_TS="75% tang300 25% song100"
DICT_C="chinese"
# default settings
USE_DICT=${DICT}

# check LANG
if [ ! -z $LC_ALL ]; then 
	LANG="$LC_ALL"
fi

# check arg
if [ ! -z $1 ]; then
	case "$1" in
	"ts")
		USE_DICT=${DICT_TS}
		;;
	"c")
		USE_DICT=${DICT_C}
		;;
	*)
		;;
	esac
fi

# output according to LANG
case "$LANG" in
"zh_CN.GB2312")
	LANG=zh_CN.UTF8 $FORTUNE $USE_DICT | iconv -c -f utf8 -t gbk
	;;
"zh_TW.Big5")
	LANG=zh_TW.UTF8 $FORTUNE $USE_DICT | iconv -c -f utf8 -t big5
	;;
*)
	$FORTUNE $USE_DICT 
	;;
esac

#EOF
