.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 Zhou Mo <cdluminate@gmail.com>,
.TH FORTUNE-ZH "6"

.SH NAME
fortune-zh \- Chinese Data files for fortune

.SH SYNOPSIS
.B fortune-zh

.SH DESCRIPTION
\fBfortune-zh\fP is a simple shell script that invokes fortune with Chinese data files.
.P
However, we recommend the use of 
.RS
$ fortune tang300
.RE
or
.RS
$ fortune song100
.RE
instead of the use of
.RS
$ fortune-zh
.RE

.SH OPTIONS
There are \fBno\fB options for fortune-zh.

.SH FILES
.TP
/usr/share/games/fortunes/tang300
.TP
/usr/share/games/fortunes/song100

.SH SEE ALSO
.BR fortune-mod (6),
.SH MANPAGE
.br
This manpage was written by Zhou Mo <cdluminate@gmail.com>
