#!/bin/bash

set -e

DICT="75% tang300 25% song100"
FORTUNE="/usr/games/fortune"

if [ ! -z $LC_ALL ] 
then 
	LANG="$LC_ALL"
fi

case "$LANG" in
"zh_CN.GB2312")
	$FORTUNE $DICT | iconv -f utf8 -t gbk
	;;
"zh_TW.Big5")
	$FORTUNE $DICT | iconv -f utf8 -t big5
	;;
*)
	$FORTUNE $DICT 
	;;
esac
