#!/bin/bash

set -e

DICT="50% tang300 15% song100 20% mingyan 15% yanyu"
FORTUNE="/usr/games/fortune"

if [ ! -z $LC_ALL ] 
then 
	LANG="$LC_ALL"
fi

case "$LANG" in
"zh_CN.GB2312")
	LANG=zh_CN.UTF8 $FORTUNE $DICT | iconv -c -f utf8 -t gbk
	;;
"zh_TW.Big5")
	LANG=zh_TW.UTF8 $FORTUNE $DICT | iconv -c -f utf8 -t big5
	;;
*)
	$FORTUNE $DICT 
	;;
esac
